from __future__ import annotations

class PayloadStreamEncoder:
    def __init__(
        self,
        encrypt_key: bytes | None = None,
        nonce: bytes | None = None,
        aad: bytes = b"",
        *,
        compression_level: int = 6,
    ) -> None: ...
    def update(self, chunk: bytes) -> bytes: ...
    def finalize(self) -> tuple[bytes, bytes | None, bytes, int, int]: ...


class PayloadCipherVerifier:
    def __init__(self, key: bytes, nonce: bytes, tag: bytes, aad: bytes = b"") -> None: ...
    def update(self, chunk: bytes) -> None: ...
    def finalize(self) -> None: ...


class PayloadStreamDecoder:
    def __init__(
        self,
        decrypt_key: bytes | None = None,
        nonce: bytes | None = None,
        tag: bytes | None = None,
        aad: bytes = b"",
        *,
        max_output_size: int = 32 * 1024 * 1024 * 1024,
    ) -> None: ...
    def update(self, chunk: bytes) -> bytes: ...
    def finalize(self) -> tuple[bytes, bytes, int]: ...


def random_bytes(length: int) -> bytes: ...
def derive_argon2id_key(
    secret: bytes,
    salt: bytes,
    *,
    length: int = 32,
    iterations: int = 3,
    lanes: int = 4,
    memory_cost_kib: int = 262144,
) -> bytes: ...
def hkdf_sha256(ikm: bytes, salt: bytes, info: bytes, *, length: int = 32) -> bytes: ...
def hkdf_sha3_256(ikm: bytes, salt: bytes | None, info: bytes, *, length: int = 32) -> bytes: ...
def aes256gcm_encrypt(key: bytes, nonce: bytes, plaintext: bytes, aad: bytes) -> bytes: ...
def aes256gcm_decrypt(key: bytes, nonce: bytes, ciphertext: bytes, aad: bytes) -> bytes: ...
def sha256_digest(data: bytes) -> bytes: ...
